doc:
	$(MAKE) -B dokumentace.pdf
	#$(MAKE) -B dokumentace.bbl
	#$(MAKE) -B dokumentace.pdf
	$(MAKE) -B dokumentace.pdf

pres:
	$(MAKE) -B prezentace.pdf
	$(MAKE) -B prezentace.pdf


include Makefile.mk